---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: workstation
# description will be included in the image's metadata
description: https://github.com/elliotblackburn/workstation

# the base image to build on top of (FROM) and the version tag to use
# base-image: ghcr.io/ublue-os/silverblue-main
base-image: ghcr.io/ublue-os/bluefin # could use dx but I'm a simple man
image-version: 43 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  # Setup terra repository which is used for installing Zed.
  - type: script
    snippets:
      - "dnf install --nogpgcheck --repofrompath 'terra,https://repos.fyralabs.com/terra$releasever' terra-release -y"

  # Install packages via dnf
  - type: dnf
    repos:
      cleanup: true
      copr:
        - ublue-os/staging
        - ublue-os/packages
        - scottames/ghostty
      files:
        - https://pkgs.tailscale.com/unstable/fedora/tailscale.repo
        - https://download.docker.com/linux/fedora/docker-ce.repo
    install:
      packages:
        - repo: copr:copr.fedorainfracloud.org:scottames:ghostty
          packages:
            - ghostty
        - repo: terra
          packages:
            - zed
        - zsh
        - tmux
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - docker-buildx-plugin
        - docker-compose-plugin
    replace:
      # We want tailscale unstable for the latest and greatest
      # and for testing.
      - from-repo: tailscale-unstable
        packages:
          - tailscale
    remove:
      packages:
        # example: removing firefox (in favor of the flatpak)
        # "firefox" is the main package, "firefox-langpacks" is a dependency
        - firefox
        - firefox-langpacks # also remove firefox dependency (not required for all packages, this is a special case)

  - type: default-flatpaks
    configurations:
      - notify: true # Send notification after install/uninstall is finished (true/false)
        scope: system
        # If no repo information is specified, Flathub will be used by default
        install: # system flatpaks we want all users to have and not remove
          - org.mozilla.firefox
          - org.gnome.Loupe
          - org.chromium.Chromium
          - com.discordapp.Discord
          - com.spotify.Client
          - org.signal.Signal
          - com.jetbrains.DataGrip
        remove:
          - org.gnome.eog # Image viewer, replaced with Loupe.
      - scope: user # Also add Flathub user repo, but no user packages

  - type: bling
    install:
      - 1password
      - dconf-update-service # a service unit that updates the dconf db on boot

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
